### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by ynghr1226** [ynghr1226/furima-32454#10]
# フリマアプリURL
https://furima-32454.herokuapp.com/

# Basic認証のIDとパスワード 
ID admin
pass 2222

# 出品者用のメールアドレスとパスワード 
yana@yana.com 
yana1226

# 購入者用のメールアドレスとパスワード 
toshi@toshi.com
toshi0210

# 購入用カード情報
番号 4242424242424242
期限 33/3
セキュリティコード123

**Comment by naru6117** [comment]
@ynghr1226さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [ ] **ログイン状態の出品者が、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**


また、必須項目ではないですが、ログイン画面の表示が崩れていました。
念の為、共有です。
こちらの項目に関しては必須でないため、修正報告は不要です(^^)
<img width="1181" alt="スクリーンショット 2021-01-05 16 28 41" src="https://user-images.githubusercontent.com/49669977/103618415-47d66b80-4f73-11eb-8fc6-0ffb767a1f3c.png">


1つ目の項目が修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、引き続き以下の不備が見受けられましたので修正をお願いします！
※マージやデプロイを忘れていないかなどもご確認ください。

### [修正依頼箇所]

- [ ] **ログイン状態の出品者が、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ynghr1226** [comment]
## 挙動
https://gyazo.com/8c8520f7f55dda2f83e89050dffd6b3e

## git
https://gyazo.com/029deb2e18268252f77aa353f87263b6

すみません、こちらですと挙動が問題なく動いておりまして、gitのpushも完了している状態なのですがどこかUPで不備がございますでしょうか？

**Comment by Ryosuke12323** [comment]
@ynghr1226 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！LGTMです✨　
おめでとうございます🎉

着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
